language: python

python:
  - "2.7"

env:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  - VERSION="8.0" UNIT_TEST="1" LINT_CHECK="0"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - sudo pip install python-ldap
  - printf '[options]\n\nrunning_env = dev' > ${HOME}/.openerp_serverrc
  - ln -s server_environment_files_sample ./server_environment_files
script:
  - travis_run_tests

after_success:
  coveralls
